// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.

export const firebaseConfig = {
  "projectId": "studio-4567469706-9b71b",
  "appId": "1:232859311623:web:9fd7fabd7347ecde2614a2",
  "apiKey": "AIzaSyBLlukZLna5NYeprJX4rSaS3_v9cx_wBsc",
  "authDomain": "studio-4567469706-9b71b.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "232859311623"
};
