// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.

export const firebaseConfig = {
  "apiKey": "mock-api-key",
  "authDomain": "mock-project-id.firebaseapp.com",
  "projectId": "mock-project-id",
  "storageBucket": "mock-project-id.appspot.com",
  "messagingSenderId": "123456789012",
  "appId": "1:123456789012:web:abcdef1234567890"
};
